import io
import logging
import os
import time
import traceback
from datetime import datetime
from typing import Any, Dict, List, Optional
from uuid import UUID, uuid4

import httpx
from fastapi import APIRouter, BackgroundTasks, Depends, HTTPException, Query
from pydantic import BaseModel
from sqlalchemy import text
from sqlalchemy.orm import Session

from app.middleware.rbac import TokenUser, require_ba, require_readonly
from app.services.db_service import get_db

logger = logging.getLogger(__name__)

QDRANT_HOST = os.environ.get("QDRANT_HOST", "qdrant")
QDRANT_PORT = int(os.environ.get("QDRANT_PORT", "6333"))
COLLECTION_NAME = os.environ.get("QDRANT_COLLECTION_NAME", "documents_embeddings")

# Allow runtime override: a neighbouring _kb_env.py file may set env vars
# before the module globals are resolved.  This file is generated by deployment
# scripts and must never be committed (it contains API keys).
try:
    from app.routers import _kb_env  # noqa: F401  # pyright: ignore[reportMissingModuleSource]
except ImportError:
    pass

OPENROUTER_API_KEY = os.environ.get("OPENROUTER_API_KEY", "")
DEEPSEEK_API_KEY = os.environ.get("DEEPSEEK_API_KEY", "")
EMBEDDING_DIM = 384

LOW_CONFIDENCE_PHRASES = [
    "do not contain",
    "cannot find",
    "not mentioned",
    "no information",
    "insufficient information",
    "not sufficient",
]

# In-memory store for search jobs
active_searches: Dict[str, Dict[str, Any]] = {}

router = APIRouter()


class AddRagDocumentsRequest(BaseModel):
    doc_ids: List[str]


@router.get("/rag")
async def get_rag_documents(
    project_id: str = Query(...),
    current_user: TokenUser = Depends(require_readonly),
    db: Session = Depends(get_db),
):
    rows = db.execute(
        text(
            """
            SELECT doc_id::text AS doc_id, status
            FROM rag_documents
            WHERE project_id = :project_id
            ORDER BY added_at DESC
            """
        ),
        {"project_id": project_id},
    ).fetchall()

    return {
        "project_id": project_id,
        "doc_ids": [row.doc_id for row in rows],
        "items": [{"doc_id": row.doc_id, "status": row.status} for row in rows],
        "count": len(rows),
    }


@router.post("/rag")
async def add_rag_documents(
    payload: AddRagDocumentsRequest,
    current_user: TokenUser = Depends(require_ba),
    db: Session = Depends(get_db),
):
    doc_ids = [doc_id.strip() for doc_id in payload.doc_ids if isinstance(doc_id, str) and doc_id.strip()]
    if not doc_ids:
        raise HTTPException(status_code=400, detail="doc_ids must not be empty")

    now = datetime.utcnow()
    inserted_doc_ids: List[str] = []

    try:
        for doc_id in doc_ids:
            row = db.execute(
                text(
                    """
                    INSERT INTO rag_documents (id, doc_id, project_id, added_by, added_at, status)
                    SELECT gen_random_uuid(), d.doc_id, d.project_id, :added_by, :added_at, 'pending'
                    FROM documents d
                    WHERE d.doc_id = :doc_id
                      AND d.status = 'approved'
                    ON CONFLICT (doc_id) DO UPDATE SET added_at = rag_documents.added_at
                    RETURNING doc_id::text AS doc_id
                    """
                ),
                {
                    "doc_id": doc_id,
                    "added_by": current_user.user_id,
                    "added_at": now,
                },
            ).fetchone()

            if row and row.doc_id:
                inserted_doc_ids.append(row.doc_id)

        db.commit()
    except Exception:
        db.rollback()
        raise HTTPException(status_code=500, detail="Failed to add documents to RAG")

    return {
        "added_count": len(inserted_doc_ids),
        "doc_ids": inserted_doc_ids,
        "message": f"{len(inserted_doc_ids)} document(s) added to RAG",
    }


# ─────────────────────────────────────────────────────────────────────────────
# Search pipeline
# ─────────────────────────────────────────────────────────────────────────────

class SearchRequest(BaseModel):
    question: str
    doc_ids: List[UUID]
    project_id: UUID
    llm_provider: str = "auto"


def _new_job(search_id: str, question: str) -> Dict[str, Any]:
    return {
        "search_id": search_id,
        "status": "processing",
        "stage_statuses": {
            "security": "idle",
            "retrieval": "idle",
            "reasoning": "idle",
            "validation": "idle",
        },
        "question": question,
        "answer": None,
        "sources": [],
        "confidence": None,
        "processing_time_ms": None,
        "error_message": None,
    }


def _extract_text_from_bytes(content: bytes, filename: str) -> Optional[str]:
    """Extract plain text from file bytes based on extension."""
    fname = filename.lower()
    try:
        if fname.endswith(".pdf"):
            from pypdf import PdfReader
            reader = PdfReader(io.BytesIO(content))
            parts = []
            for page in reader.pages:
                t = page.extract_text()
                if t:
                    parts.append(t)
            return "\n".join(parts)
        elif fname.endswith(".docx"):
            from docx import Document
            doc = Document(io.BytesIO(content))
            return "\n".join(p.text for p in doc.paragraphs if p.text)
        elif fname.endswith((".xlsx", ".xls")):
            import openpyxl
            wb = openpyxl.load_workbook(io.BytesIO(content), read_only=True, data_only=True)
            parts = []
            for sheet in wb.worksheets:
                parts.append(f"=== Sheet: {sheet.title} ===")
                for row in sheet.iter_rows(values_only=True):
                    row_text = "\t".join(str(cell) if cell is not None else "" for cell in row)
                    if row_text.strip():
                        parts.append(row_text)
            return "\n".join(parts)
        elif fname.endswith((".txt", ".md", ".csv")):
            return content.decode("utf-8", errors="replace")
        elif fname.endswith((".png", ".jpg", ".jpeg", ".gif", ".bmp", ".webp")):
            return None  # images not supported
        else:
            # attempt plain text decode for unknown types
            return content.decode("utf-8", errors="replace")
    except Exception as exc:
        logger.warning("text_extraction_failed file=%s err=%s", filename, exc)
        return None


def _chunk_text(text: str, chunk_size: int = 500, overlap: int = 50) -> List[str]:
    chunks = []
    start = 0
    while start < len(text):
        end = start + chunk_size
        chunks.append(text[start:end])
        start += chunk_size - overlap
    return [c for c in chunks if c.strip()]


def _download_from_drive(file_id: str) -> Optional[bytes]:
    """Download raw bytes from Google Drive using the service credentials."""
    try:
        from app.services.google_drive import _build_service
        service = _build_service()
        if service is None:
            return None
        request = service.files().get_media(fileId=file_id)
        buf = io.BytesIO()
        from googleapiclient.http import MediaIoBaseDownload
        downloader = MediaIoBaseDownload(buf, request)
        done = False
        while not done:
            _, done = downloader.next_chunk()
        return buf.getvalue()
    except Exception as exc:
        logger.warning("google_drive_download_failed file_id=%s err=%s", file_id, exc)
        return None


async def _run_search_pipeline(
    search_id: str,
    question: str,
    doc_ids: List[UUID],
    project_id: UUID,
    user_id: str,
    user_projects: List[str],
    db: Session,
    llm_provider: str = "auto",
) -> None:
    job = active_searches[search_id]
    start_time = time.time()

    try:
        # ── STAGE 1: Security ──────────────────────────────────────────────
        job["stage_statuses"]["security"] = "working"

        # Check user project access
        if str(project_id) not in user_projects:
            job["stage_statuses"]["security"] = "error"
            job["status"] = "error"
            job["error_message"] = "Access denied: you do not have access to this project"
            return

        # Verify all doc_ids belong to project_id and are approved
        doc_ids_str = [str(d) for d in doc_ids]
        placeholders = ", ".join(f":doc_{i}" for i in range(len(doc_ids_str)))
        params: Dict[str, Any] = {"project_id": str(project_id)}
        for i, d in enumerate(doc_ids_str):
            params[f"doc_{i}"] = d

        rows = db.execute(
            text(
                f"""
                SELECT doc_id::text AS doc_id, status, project_id::text AS project_id
                FROM documents
                WHERE doc_id IN ({placeholders})
                """
            ),
            params,
        ).fetchall()

        if len(rows) != len(doc_ids_str):
            job["stage_statuses"]["security"] = "error"
            job["status"] = "error"
            job["error_message"] = "One or more documents not found"
            return

        for row in rows:
            if row.project_id != str(project_id):
                job["stage_statuses"]["security"] = "error"
                job["status"] = "error"
                job["error_message"] = f"Document {row.doc_id} does not belong to project {project_id}"
                return
            if row.status != "approved":
                job["stage_statuses"]["security"] = "error"
                job["status"] = "error"
                job["error_message"] = f"Document {row.doc_id} is not approved (status: {row.status})"
                return

        job["stage_statuses"]["security"] = "done"

        # ── STAGE 2: Retrieval ─────────────────────────────────────────────
        job["stage_statuses"]["retrieval"] = "working"

        try:
            from qdrant_client import QdrantClient
            from qdrant_client.models import (
                Distance,
                FieldCondition,
                Filter,
                MatchAny,
                MatchValue,
                PointStruct,
                VectorParams,
            )
        except ImportError as exc:
            logger.error("Stage retrieval failed: %s", str(exc))
            logger.error(traceback.format_exc())
            job["stage_statuses"]["retrieval"] = "error"
            job["status"] = "error"
            job["error_message"] = f"qdrant-client not available: {exc}"
            return

        qdrant = QdrantClient(host=QDRANT_HOST, port=QDRANT_PORT)

        # Ensure collection exists
        existing = [c.name for c in qdrant.get_collections().collections]
        if COLLECTION_NAME not in existing:
            qdrant.create_collection(
                collection_name=COLLECTION_NAME,
                vectors_config=VectorParams(size=EMBEDDING_DIM, distance=Distance.COSINE),
            )

        try:
            from sentence_transformers import SentenceTransformer
            st_model = SentenceTransformer("sentence-transformers/all-MiniLM-L6-v2")
        except Exception as exc:
            logger.error("Stage retrieval failed: %s", str(exc))
            logger.error(traceback.format_exc())
            job["stage_statuses"]["retrieval"] = "error"
            job["status"] = "error"
            job["error_message"] = f"sentence-transformers unavailable: {exc}"
            return

        for doc_id in doc_ids:
            doc_id_str = str(doc_id)

            # Check if already embedded
            existing_results = qdrant.search(
                collection_name=COLLECTION_NAME,
                query_vector=[0.0] * EMBEDDING_DIM,
                query_filter=Filter(
                    must=[FieldCondition(key="doc_id", match=MatchValue(value=doc_id_str))]
                ),
                limit=1,
            )
            if existing_results:
                continue  # already indexed

            # Fetch document metadata
            doc_row = db.execute(
                text(
                    """
                    SELECT title, google_drive_link, doc_type
                    FROM documents
                    WHERE doc_id = :doc_id
                    """
                ),
                {"doc_id": doc_id_str},
            ).fetchone()

            if not doc_row:
                continue

            title = doc_row.title or "Untitled"
            drive_link = doc_row.google_drive_link or ""
            # Use title as filename (it typically contains the original filename with extension)
            file_name = title

            # Extract Drive file ID from link
            from app.services.google_drive import get_drive_file_id
            drive_file_id = get_drive_file_id(drive_link) if drive_link else None

            content_bytes: Optional[bytes] = None
            if drive_file_id:
                content_bytes = _download_from_drive(drive_file_id)

            if content_bytes is None:
                logger.warning("skip_embedding doc_id=%s reason=download_failed", doc_id_str)
                continue

            text_content = _extract_text_from_bytes(content_bytes, file_name)
            if not text_content:
                logger.warning("skip_embedding doc_id=%s reason=no_text_extracted", doc_id_str)
                continue

            chunks = _chunk_text(text_content)
            if not chunks:
                continue

            embeddings = st_model.encode(chunks, normalize_embeddings=True).tolist()
            points = [
                PointStruct(
                    id=str(uuid4()),
                    vector=embeddings[i],
                    payload={
                        "doc_id": doc_id_str,
                        "project_id": str(project_id),
                        "chunk_index": i,
                        "chunk_text": chunks[i],
                        "title": title,
                    },
                )
                for i in range(len(chunks))
            ]
            qdrant.upsert(collection_name=COLLECTION_NAME, points=points)

        job["stage_statuses"]["retrieval"] = "done"

        # ── STAGE 3: Reasoning ─────────────────────────────────────────────
        job["stage_statuses"]["reasoning"] = "working"

        question_embedding = st_model.encode([question], normalize_embeddings=True)[0].tolist()

        search_results = qdrant.search(
            collection_name=COLLECTION_NAME,
            query_vector=question_embedding,
            query_filter=Filter(
                must=[
                    FieldCondition(
                        key="doc_id",
                        match=MatchAny(any=[str(d) for d in doc_ids]),
                    )
                ]
            ),
            limit=5,
        )

        if not search_results:
            job["stage_statuses"]["reasoning"] = "done"
            job["stage_statuses"]["validation"] = "done"
            job["status"] = "completed"
            job["answer"] = "The provided documents do not contain sufficient information to answer this question."
            job["sources"] = []
            job["confidence"] = "low"
            job["processing_time_ms"] = int((time.time() - start_time) * 1000)
            return

        excerpts = []
        for i, result in enumerate(search_results):
            payload = result.payload or {}
            excerpts.append(
                f"[Excerpt {i + 1} - Source: {payload.get('title', 'Unknown')}]\n"
                f"{payload.get('chunk_text', '')}"
            )

        system_msg = (
            "You are a precise document analyst assistant. "
            "Answer the user's question based STRICTLY on the provided document excerpts below.\n\n"
            "Rules:\n"
            "1. Only use information from the provided excerpts\n"
            "2. If the answer cannot be found in the excerpts, respond with exactly: "
            "'The provided documents do not contain sufficient information to answer this question.'\n"
            "3. Do not use any external knowledge or assumptions\n"
            "4. Reference which document each key point comes from\n"
            "5. Be concise, factual and well-structured"
        )
        user_msg = "Document excerpts:\n\n" + "\n\n".join(excerpts) + f"\n\nQuestion: {question}"

        llm_answer: Optional[str] = None
        _OPENROUTER_MODEL_MAP = {
            "openrouter":       "openai/gpt-4o-mini",
            "gemini-2.5-pro":   "google/gemini-2.5-pro-preview-03-25",
            "minimax-m2.5":     "minimax/minimax-m1",
            "claude-haiku-4-5": "anthropic/claude-haiku-4-5",
        }
        use_openrouter = llm_provider in {"auto", "openrouter", "gemini-2.5-pro", "minimax-m2.5", "claude-haiku-4-5"}
        use_deepseek = llm_provider in ("auto", "deepseek")
        openrouter_model_id = _OPENROUTER_MODEL_MAP.get(llm_provider, "openai/gpt-4o-mini")

        # Primary: DeepSeek (or OpenRouter if explicitly selected)
        if DEEPSEEK_API_KEY and use_deepseek:
            try:
                async with httpx.AsyncClient(timeout=httpx.Timeout(600.0, connect=15.0, read=600.0)) as client:
                    resp = await client.post(
                        "https://api.deepseek.com/chat/completions",
                        headers={"Authorization": f"Bearer {DEEPSEEK_API_KEY}"},
                        json={
                            "model": "deepseek-chat",
                            "messages": [
                                {"role": "system", "content": system_msg},
                                {"role": "user", "content": user_msg},
                            ],
                            "max_tokens": 1000,
                            "temperature": 0.1,
                        },
                    )
                    if resp.status_code == 200:
                        data = resp.json()
                        llm_answer = data["choices"][0]["message"]["content"]
            except Exception as exc:
                logger.error("Stage reasoning failed (deepseek): %s", str(exc))
                logger.error(traceback.format_exc())

        # Fallback: OpenRouter
        if llm_answer is None and OPENROUTER_API_KEY and use_openrouter:
            try:
                async with httpx.AsyncClient(timeout=httpx.Timeout(600.0, connect=15.0, read=600.0)) as client:
                    resp = await client.post(
                        "https://openrouter.ai/api/v1/chat/completions",
                        headers={"Authorization": f"Bearer {OPENROUTER_API_KEY}"},
                        json={
                            "model": openrouter_model_id,
                            "messages": [
                                {"role": "system", "content": system_msg},
                                {"role": "user", "content": user_msg},
                            ],
                            "max_tokens": 1000,
                            "temperature": 0.1,
                        },
                    )
                    if resp.status_code == 200:
                        data = resp.json()
                        llm_answer = data["choices"][0]["message"]["content"]
            except Exception as exc:
                logger.error("Stage reasoning failed (openrouter): %s", str(exc))
                logger.error(traceback.format_exc())

        if llm_answer is None:
            llm_answer = "The provided documents do not contain sufficient information to answer this question."

        # Build sources list
        sources_map: Dict[str, Dict[str, Any]] = {}
        for result in search_results:
            payload = result.payload or {}
            did = payload.get("doc_id", "")
            if did not in sources_map:
                sources_map[did] = {"doc_id": did, "title": payload.get("title", "Unknown"), "chunks_used": 0}
            sources_map[did]["chunks_used"] += 1
        sources_list = list(sources_map.values())

        job["stage_statuses"]["reasoning"] = "done"

        # ── STAGE 4: Validation ────────────────────────────────────────────
        job["stage_statuses"]["validation"] = "working"

        answer_lower = llm_answer.lower()
        confidence = "low" if any(phrase in answer_lower for phrase in LOW_CONFIDENCE_PHRASES) else "high"

        elapsed_ms = int((time.time() - start_time) * 1000)
        job["status"] = "completed"
        job["answer"] = llm_answer
        job["sources"] = sources_list
        job["confidence"] = confidence
        job["processing_time_ms"] = elapsed_ms
        job["stage_statuses"]["validation"] = "done"

    except Exception as exc:
        logger.error("Stage pipeline (outer) failed: %s", str(exc))
        logger.error(traceback.format_exc())
        # Mark whatever stage was last active as error
        for stage in ("security", "retrieval", "reasoning", "validation"):
            if job["stage_statuses"][stage] == "working":
                job["stage_statuses"][stage] = "error"
                break
        job["status"] = "error"
        job["error_message"] = "An unexpected error occurred during search. Please try again."
    finally:
        db.close()


@router.post("/search")
async def start_search(
    payload: SearchRequest,
    background_tasks: BackgroundTasks,
    current_user: TokenUser = Depends(require_readonly),
    db: Session = Depends(get_db),
):
    if not payload.question.strip():
        raise HTTPException(status_code=400, detail="question must not be empty")
    if not payload.doc_ids:
        raise HTTPException(status_code=400, detail="doc_ids must not be empty")

    search_id = str(uuid4())
    active_searches[search_id] = _new_job(search_id, payload.question)

    background_tasks.add_task(
        _run_search_pipeline,
        search_id=search_id,
        question=payload.question,
        doc_ids=payload.doc_ids,
        project_id=payload.project_id,
        user_id=current_user.user_id,
        user_projects=current_user.projects,
        db=db,
        llm_provider=payload.llm_provider,
    )

    return {"search_id": search_id}


@router.get("/search/{search_id}/status")
async def get_search_status(
    search_id: str,
    current_user: TokenUser = Depends(require_readonly),
):
    job = active_searches.get(search_id)
    if job is None:
        raise HTTPException(status_code=404, detail="Search job not found or expired")
    return job
